[[!comment format=mdwn
 username="joey"
 subject="""comment 1"""
 date="2019-05-23T16:18:23Z"
 content="""
This may be somehow related to the other bug in that it might also have to
do with the same temp file, but it does not seem to be the same problem.

Why would rename() be failing with a permissions problem due to a temp
directory cleanup?

It would be helpful to see a strace of the failed `rename()` call, because
I can't immadiately see where a temp file with that name would be exposed
to `rename()` in a way that could crash like that.
"""]]
