### Please describe the problem.

This is a followup on [[bugs/internal_server_error:_unknown_UUID_on_webapp]]. In that issue, webapps previous to 20130929 would crash with `internal server error: unknown UUID`. This was fixed at that date, but some problems remain, namely that the remote that is recognized on the commandline doesn't show up in the webapp.

`markov` is able to push to `marcos`, but not the reverse because `markov` is hidden behind a NAT. `git annex sync` seems to do the right thing accordingly on both ends.

### What steps will reproduce the problem?

See [[bugs/internal_server_error:_unknown_UUID_on_webapp]]. I didn't do any further changes other than upgrade git-annex on both ends.

### What version of git-annex are you using? On what operating system?

`marcos` is now running `Version: 4.20131105-g8efdc1a Build flags: Assistant Webapp Pairing Testsuite S3 WebDAV Inotify DBus XMPP DNS Feeds Quvi TDFA CryptoHash`

`markov` is now running the wheezy backport, `4.20131002~bpo70+1`.

### Please provide any additional information below.

[[!format sh """
# If you can, paste a complete transcript of the problem occurring here.
# If the problem is with the git-annex assistant, paste in .git/annex/daemon.log
anarcat@marcos:books$ git annex status
repository mode: direct
trusted repositories: 0
semitrusted repositories: 3
        00000000-0000-0000-0000-000000000001 -- web
        a75cbbf7-e055-423e-b375-443e0552c9e2 -- here (anarcat@marcos:/srv/books)
        aa500f29-42d9-4777-ae02-4a2c3d47db44 -- anarcat@markov:~/books
untrusted repositories: 0
transfers in progress: none
available local disk space: 7.04 gigabytes (+1 megabyte reserved)
local annex keys: 736
local annex size: 3.92 gigabytes
annexed files in working tree: 721
size of annexed files in working tree: 3.92 gigabytes
bloom filter size: 16 mebibytes (0.1% full)
backend usage:
        SHA256E: 1457
# End of transcript or log.
"""]]

Here's a screenshot of the webapp:

<img src="http://i.imgur.com/3HFgj3w.png" />

You can clearly see that the webapp doesn't see the `markov` remote. When `markov` transfers stuff, `marcos` sees the transfers happening, but marks it as going to the `unknown` remote. Clicking on that link is what was previously triggering [[bugs/internal_server_error:_unknown_UUID_on_webapp]] but now yields a "Unknown remote" error (which I can't reproduce anymore because the repos are synced - I can reproduce by retransfering some files if necessary). --[[anarcat]]
